# Generated by Django 3.2 on 2021-04-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_walking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walking',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='walking',
            name='date',
            field=models.DateField(verbose_name='walk date'),
        ),
        migrations.AlterField(
            model_name='walking',
            name='potty',
            field=models.CharField(choices=[('0', 'No Potty'), ('1', 'Pee'), ('2', 'Poo'), ('3', 'Pee + Poo')], default='0', max_length=1),
        ),
    ]
