# Generated by Django 3.2 on 2021-04-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_walking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walking',
            name='time',
            field=models.TimeField(),
        ),
    ]
