# Generated by Django 3.2 on 2021-04-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_walking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='walking',
            name='potty',
            field=models.CharField(choices=[('0', 'N/A'), ('1', 'Pee'), ('2', 'Poo'), ('3', 'Both')], default='0', max_length=1),
        ),
    ]
