# Generated by Django 3.2 on 2021-04-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210421_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='foods',
            field=models.ManyToManyField(to='main_app.Food'),
        ),
    ]
