# Generated by Django 3.2 on 2021-04-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_food_flavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food',
            new_name='type',
        ),
    ]
